name: Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-dev python3-venv
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run Python tests
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install --upgrade pip
          pip3 install maturin
          make test_py
